.TH urss 1 "30 May 23"
.SH NAME
urss \- generate an RSS feed from HTML files
.SH SYNOPSIS
\fBurss\fP
.SH DESCRIPTION
\fBurss\fP reads HTML files from standard input to produce an RSS feed to standard output.
urss can be customised by creating a custom config.h, editing urss.c, and (re)compiling the source code.
This keeps it fast, secure and simple.

.SH BUGS
Report bugs to either <\fIgithub.com/u20n/urss\fP> or <\fIgitlab.com/u2on/urss\fP>

.SH Authors
u2on: <\fIgit@notu.dev\fP>
